//! Generated by scripts/generate-bindings.py.
//!
//! Takes the address of every function declared for the enabled
//! `clang_<major>_0` features, so that this test fails to link if the
//! libclang it is linked with lacks any of them.

use std::hint::black_box;

use clang_rs_sys::*;

#[test]
fn every_declared_function_links() {
    black_box(clang_getCString as *const ());
    black_box(clang_disposeString as *const ());
    black_box(clang_disposeStringSet as *const ());
    black_box(clang_getBuildSessionTimestamp as *const ());
    black_box(clang_VirtualFileOverlay_create as *const ());
    black_box(clang_VirtualFileOverlay_addFileMapping as *const ());
    black_box(clang_VirtualFileOverlay_setCaseSensitivity as *const ());
    black_box(clang_VirtualFileOverlay_writeToBuffer as *const ());
    black_box(clang_free as *const ());
    black_box(clang_VirtualFileOverlay_dispose as *const ());
    black_box(clang_ModuleMapDescriptor_create as *const ());
    black_box(clang_ModuleMapDescriptor_setFrameworkModuleName as *const ());
    black_box(clang_ModuleMapDescriptor_setUmbrellaHeader as *const ());
    black_box(clang_ModuleMapDescriptor_writeToBuffer as *const ());
    black_box(clang_ModuleMapDescriptor_dispose as *const ());
    #[cfg(any(feature = "clang_23_0", not(feature = "clang_14_0")))]
    black_box(clang_ModuleCache_prune as *const ());
    #[cfg(any(feature = "clang_23_0", not(feature = "clang_14_0")))]
    black_box(clang_ModuleCache_pruneWithCallback as *const ());
    black_box(clang_CompilationDatabase_fromDirectory as *const ());
    black_box(clang_CompilationDatabase_dispose as *const ());
    black_box(clang_CompilationDatabase_getCompileCommands as *const ());
    black_box(clang_CompilationDatabase_getAllCompileCommands as *const ());
    black_box(clang_CompileCommands_dispose as *const ());
    black_box(clang_CompileCommands_getSize as *const ());
    black_box(clang_CompileCommands_getCommand as *const ());
    black_box(clang_CompileCommand_getDirectory as *const ());
    black_box(clang_CompileCommand_getFilename as *const ());
    black_box(clang_CompileCommand_getNumArgs as *const ());
    black_box(clang_CompileCommand_getArg as *const ());
    black_box(clang_CompileCommand_getNumMappedSources as *const ());
    black_box(clang_CompileCommand_getMappedSourcePath as *const ());
    black_box(clang_CompileCommand_getMappedSourceContent as *const ());
    black_box(clang_getFileName as *const ());
    black_box(clang_getFileTime as *const ());
    black_box(clang_getFileUniqueID as *const ());
    black_box(clang_File_isEqual as *const ());
    black_box(clang_File_tryGetRealPathName as *const ());
    black_box(clang_getNullLocation as *const ());
    black_box(clang_equalLocations as *const ());
    #[cfg(any(feature = "clang_20_0", not(feature = "clang_14_0")))]
    black_box(clang_isBeforeInTranslationUnit as *const ());
    black_box(clang_Location_isInSystemHeader as *const ());
    black_box(clang_Location_isFromMainFile as *const ());
    black_box(clang_getNullRange as *const ());
    black_box(clang_getRange as *const ());
    black_box(clang_equalRanges as *const ());
    black_box(clang_Range_isNull as *const ());
    black_box(clang_getExpansionLocation as *const ());
    black_box(clang_getPresumedLocation as *const ());
    black_box(clang_getInstantiationLocation as *const ());
    black_box(clang_getSpellingLocation as *const ());
    black_box(clang_getFileLocation as *const ());
    black_box(clang_getRangeStart as *const ());
    black_box(clang_getRangeEnd as *const ());
    black_box(clang_disposeSourceRangeList as *const ());
    black_box(clang_getNumDiagnosticsInSet as *const ());
    black_box(clang_getDiagnosticInSet as *const ());
    black_box(clang_loadDiagnostics as *const ());
    black_box(clang_disposeDiagnosticSet as *const ());
    black_box(clang_getChildDiagnostics as *const ());
    black_box(clang_disposeDiagnostic as *const ());
    black_box(clang_formatDiagnostic as *const ());
    black_box(clang_defaultDiagnosticDisplayOptions as *const ());
    black_box(clang_getDiagnosticSeverity as *const ());
    black_box(clang_getDiagnosticLocation as *const ());
    black_box(clang_getDiagnosticSpelling as *const ());
    black_box(clang_getDiagnosticOption as *const ());
    black_box(clang_getDiagnosticCategory as *const ());
    black_box(clang_getDiagnosticCategoryName as *const ());
    black_box(clang_getDiagnosticCategoryText as *const ());
    black_box(clang_getDiagnosticNumRanges as *const ());
    black_box(clang_getDiagnosticRange as *const ());
    black_box(clang_getDiagnosticNumFixIts as *const ());
    black_box(clang_getDiagnosticFixIt as *const ());
    black_box(clang_createIndex as *const ());
    black_box(clang_disposeIndex as *const ());
    #[cfg(any(feature = "clang_17_0", not(feature = "clang_14_0")))]
    black_box(clang_createIndexWithOptions as *const ());
    black_box(clang_CXIndex_setGlobalOptions as *const ());
    black_box(clang_CXIndex_getGlobalOptions as *const ());
    black_box(clang_CXIndex_setInvocationEmissionPathOption as *const ());
    black_box(clang_isFileMultipleIncludeGuarded as *const ());
    black_box(clang_getFile as *const ());
    black_box(clang_getFileContents as *const ());
    black_box(clang_getLocation as *const ());
    black_box(clang_getLocationForOffset as *const ());
    black_box(clang_getSkippedRanges as *const ());
    black_box(clang_getAllSkippedRanges as *const ());
    black_box(clang_getNumDiagnostics as *const ());
    black_box(clang_getDiagnostic as *const ());
    black_box(clang_getDiagnosticSetFromTU as *const ());
    black_box(clang_getTranslationUnitSpelling as *const ());
    black_box(clang_createTranslationUnitFromSourceFile as *const ());
    black_box(clang_createTranslationUnit as *const ());
    black_box(clang_createTranslationUnit2 as *const ());
    black_box(clang_defaultEditingTranslationUnitOptions as *const ());
    black_box(clang_parseTranslationUnit as *const ());
    black_box(clang_parseTranslationUnit2 as *const ());
    black_box(clang_parseTranslationUnit2FullArgv as *const ());
    black_box(clang_defaultSaveOptions as *const ());
    black_box(clang_saveTranslationUnit as *const ());
    black_box(clang_suspendTranslationUnit as *const ());
    black_box(clang_disposeTranslationUnit as *const ());
    black_box(clang_defaultReparseOptions as *const ());
    black_box(clang_reparseTranslationUnit as *const ());
    black_box(clang_getTUResourceUsageName as *const ());
    black_box(clang_getCXTUResourceUsage as *const ());
    black_box(clang_disposeCXTUResourceUsage as *const ());
    black_box(clang_getTranslationUnitTargetInfo as *const ());
    black_box(clang_TargetInfo_dispose as *const ());
    black_box(clang_TargetInfo_getTriple as *const ());
    black_box(clang_TargetInfo_getPointerWidth as *const ());
    black_box(clang_getNullCursor as *const ());
    black_box(clang_getTranslationUnitCursor as *const ());
    black_box(clang_equalCursors as *const ());
    black_box(clang_Cursor_isNull as *const ());
    black_box(clang_hashCursor as *const ());
    black_box(clang_getCursorKind as *const ());
    black_box(clang_isDeclaration as *const ());
    black_box(clang_isInvalidDeclaration as *const ());
    black_box(clang_isReference as *const ());
    black_box(clang_isExpression as *const ());
    black_box(clang_isStatement as *const ());
    black_box(clang_isAttribute as *const ());
    black_box(clang_Cursor_hasAttrs as *const ());
    black_box(clang_isInvalid as *const ());
    black_box(clang_isTranslationUnit as *const ());
    black_box(clang_isPreprocessing as *const ());
    black_box(clang_isUnexposed as *const ());
    black_box(clang_getCursorLinkage as *const ());
    black_box(clang_getCursorVisibility as *const ());
    black_box(clang_getCursorAvailability as *const ());
    black_box(clang_getCursorPlatformAvailability as *const ());
    black_box(clang_disposeCXPlatformAvailability as *const ());
    black_box(clang_Cursor_getVarDeclInitializer as *const ());
    black_box(clang_Cursor_hasVarDeclGlobalStorage as *const ());
    black_box(clang_Cursor_hasVarDeclExternalStorage as *const ());
    black_box(clang_getCursorLanguage as *const ());
    black_box(clang_getCursorTLSKind as *const ());
    black_box(clang_Cursor_getTranslationUnit as *const ());
    black_box(clang_createCXCursorSet as *const ());
    black_box(clang_disposeCXCursorSet as *const ());
    black_box(clang_CXCursorSet_contains as *const ());
    black_box(clang_CXCursorSet_insert as *const ());
    black_box(clang_getCursorSemanticParent as *const ());
    black_box(clang_getCursorLexicalParent as *const ());
    black_box(clang_getOverriddenCursors as *const ());
    black_box(clang_disposeOverriddenCursors as *const ());
    black_box(clang_getIncludedFile as *const ());
    black_box(clang_getCursor as *const ());
    black_box(clang_getCursorLocation as *const ());
    black_box(clang_getCursorExtent as *const ());
    black_box(clang_getCursorType as *const ());
    black_box(clang_getTypeSpelling as *const ());
    black_box(clang_getTypedefDeclUnderlyingType as *const ());
    black_box(clang_getEnumDeclIntegerType as *const ());
    black_box(clang_getEnumConstantDeclValue as *const ());
    black_box(clang_getEnumConstantDeclUnsignedValue as *const ());
    black_box(clang_Cursor_isBitField as *const ());
    black_box(clang_getFieldDeclBitWidth as *const ());
    black_box(clang_Cursor_getNumArguments as *const ());
    black_box(clang_Cursor_getArgument as *const ());
    black_box(clang_Cursor_getNumTemplateArguments as *const ());
    black_box(clang_Cursor_getTemplateArgumentKind as *const ());
    black_box(clang_Cursor_getTemplateArgumentType as *const ());
    black_box(clang_Cursor_getTemplateArgumentValue as *const ());
    black_box(clang_Cursor_getTemplateArgumentUnsignedValue as *const ());
    black_box(clang_equalTypes as *const ());
    black_box(clang_getCanonicalType as *const ());
    black_box(clang_isConstQualifiedType as *const ());
    black_box(clang_Cursor_isMacroFunctionLike as *const ());
    black_box(clang_Cursor_isMacroBuiltin as *const ());
    black_box(clang_Cursor_isFunctionInlined as *const ());
    black_box(clang_isVolatileQualifiedType as *const ());
    black_box(clang_isRestrictQualifiedType as *const ());
    black_box(clang_getAddressSpace as *const ());
    black_box(clang_getTypedefName as *const ());
    black_box(clang_getPointeeType as *const ());
    #[cfg(any(feature = "clang_16_0", not(feature = "clang_14_0")))]
    black_box(clang_getUnqualifiedType as *const ());
    #[cfg(any(feature = "clang_16_0", not(feature = "clang_14_0")))]
    black_box(clang_getNonReferenceType as *const ());
    black_box(clang_getTypeDeclaration as *const ());
    black_box(clang_getDeclObjCTypeEncoding as *const ());
    black_box(clang_Type_getObjCEncoding as *const ());
    black_box(clang_getTypeKindSpelling as *const ());
    black_box(clang_getFunctionTypeCallingConv as *const ());
    black_box(clang_getResultType as *const ());
    black_box(clang_getExceptionSpecificationType as *const ());
    black_box(clang_getNumArgTypes as *const ());
    black_box(clang_getArgType as *const ());
    black_box(clang_Type_getObjCObjectBaseType as *const ());
    black_box(clang_Type_getNumObjCProtocolRefs as *const ());
    black_box(clang_Type_getObjCProtocolDecl as *const ());
    black_box(clang_Type_getNumObjCTypeArgs as *const ());
    black_box(clang_Type_getObjCTypeArg as *const ());
    black_box(clang_isFunctionTypeVariadic as *const ());
    black_box(clang_getCursorResultType as *const ());
    black_box(clang_getCursorExceptionSpecificationType as *const ());
    black_box(clang_isPODType as *const ());
    black_box(clang_getElementType as *const ());
    black_box(clang_getNumElements as *const ());
    black_box(clang_getArrayElementType as *const ());
    black_box(clang_getArraySize as *const ());
    black_box(clang_Type_getNamedType as *const ());
    black_box(clang_Type_isTransparentTagTypedef as *const ());
    black_box(clang_Type_getNullability as *const ());
    black_box(clang_Type_getAlignOf as *const ());
    black_box(clang_Type_getClassType as *const ());
    black_box(clang_Type_getSizeOf as *const ());
    black_box(clang_Type_getOffsetOf as *const ());
    black_box(clang_Type_getModifiedType as *const ());
    black_box(clang_Type_getValueType as *const ());
    black_box(clang_Cursor_getOffsetOfField as *const ());
    black_box(clang_Cursor_isAnonymous as *const ());
    black_box(clang_Cursor_isAnonymousRecordDecl as *const ());
    black_box(clang_Cursor_isInlineNamespace as *const ());
    black_box(clang_Type_getNumTemplateArguments as *const ());
    black_box(clang_Type_getTemplateArgumentAsType as *const ());
    black_box(clang_Type_getCXXRefQualifier as *const ());
    black_box(clang_isVirtualBase as *const ());
    #[cfg(any(feature = "clang_20_0", not(feature = "clang_14_0")))]
    black_box(clang_getOffsetOfBase as *const ());
    black_box(clang_getCXXAccessSpecifier as *const ());
    #[cfg(any(feature = "clang_19_0", not(feature = "clang_14_0")))]
    black_box(clang_Cursor_getBinaryOpcode as *const ());
    #[cfg(any(feature = "clang_19_0", not(feature = "clang_14_0")))]
    black_box(clang_Cursor_getBinaryOpcodeStr as *const ());
    black_box(clang_Cursor_getStorageClass as *const ());
    black_box(clang_getNumOverloadedDecls as *const ());
    black_box(clang_getOverloadedDecl as *const ());
    black_box(clang_getIBOutletCollectionType as *const ());
    black_box(clang_visitChildren as *const ());
    #[cfg(any(feature = "clang_17_0", not(feature = "clang_14_0")))]
    black_box(clang_visitChildrenWithBlock as *const ());
    black_box(clang_getCursorUSR as *const ());
    black_box(clang_constructUSR_ObjCClass as *const ());
    black_box(clang_constructUSR_ObjCCategory as *const ());
    black_box(clang_constructUSR_ObjCProtocol as *const ());
    black_box(clang_constructUSR_ObjCIvar as *const ());
    black_box(clang_constructUSR_ObjCMethod as *const ());
    black_box(clang_constructUSR_ObjCProperty as *const ());
    black_box(clang_getCursorSpelling as *const ());
    black_box(clang_Cursor_getSpellingNameRange as *const ());
    black_box(clang_PrintingPolicy_getProperty as *const ());
    black_box(clang_PrintingPolicy_setProperty as *const ());
    black_box(clang_getCursorPrintingPolicy as *const ());
    black_box(clang_PrintingPolicy_dispose as *const ());
    black_box(clang_getCursorPrettyPrinted as *const ());
    #[cfg(any(feature = "clang_20_0", not(feature = "clang_14_0")))]
    black_box(clang_getTypePrettyPrinted as *const ());
    #[cfg(any(feature = "clang_21_0", not(feature = "clang_14_0")))]
    black_box(clang_getFullyQualifiedName as *const ());
    black_box(clang_getCursorDisplayName as *const ());
    black_box(clang_getCursorReferenced as *const ());
    black_box(clang_getCursorDefinition as *const ());
    black_box(clang_isCursorDefinition as *const ());
    black_box(clang_getCanonicalCursor as *const ());
    black_box(clang_Cursor_getObjCSelectorIndex as *const ());
    black_box(clang_Cursor_isDynamicCall as *const ());
    black_box(clang_Cursor_getReceiverType as *const ());
    black_box(clang_Cursor_getObjCPropertyAttributes as *const ());
    black_box(clang_Cursor_getObjCPropertyGetterName as *const ());
    black_box(clang_Cursor_getObjCPropertySetterName as *const ());
    black_box(clang_Cursor_getObjCDeclQualifiers as *const ());
    black_box(clang_Cursor_isObjCOptional as *const ());
    black_box(clang_Cursor_isVariadic as *const ());
    black_box(clang_Cursor_isExternalSymbol as *const ());
    black_box(clang_Cursor_getCommentRange as *const ());
    black_box(clang_Cursor_getRawCommentText as *const ());
    black_box(clang_Cursor_getBriefCommentText as *const ());
    black_box(clang_Cursor_getMangling as *const ());
    black_box(clang_Cursor_getCXXManglings as *const ());
    black_box(clang_Cursor_getObjCManglings as *const ());
    #[cfg(any(feature = "clang_21_0", not(feature = "clang_14_0")))]
    black_box(clang_Cursor_getGCCAssemblyTemplate as *const ());
    #[cfg(any(feature = "clang_21_0", not(feature = "clang_14_0")))]
    black_box(clang_Cursor_isGCCAssemblyHasGoto as *const ());
    #[cfg(any(feature = "clang_21_0", not(feature = "clang_14_0")))]
    black_box(clang_Cursor_getGCCAssemblyNumOutputs as *const ());
    #[cfg(any(feature = "clang_21_0", not(feature = "clang_14_0")))]
    black_box(clang_Cursor_getGCCAssemblyNumInputs as *const ());
    #[cfg(any(feature = "clang_21_0", not(feature = "clang_14_0")))]
    black_box(clang_Cursor_getGCCAssemblyInput as *const ());
    #[cfg(any(feature = "clang_21_0", not(feature = "clang_14_0")))]
    black_box(clang_Cursor_getGCCAssemblyOutput as *const ());
    #[cfg(any(feature = "clang_21_0", not(feature = "clang_14_0")))]
    black_box(clang_Cursor_getGCCAssemblyNumClobbers as *const ());
    #[cfg(any(feature = "clang_21_0", not(feature = "clang_14_0")))]
    black_box(clang_Cursor_getGCCAssemblyClobber as *const ());
    #[cfg(any(feature = "clang_21_0", not(feature = "clang_14_0")))]
    black_box(clang_Cursor_isGCCAssemblyVolatile as *const ());
    black_box(clang_Cursor_getModule as *const ());
    black_box(clang_getModuleForFile as *const ());
    black_box(clang_Module_getASTFile as *const ());
    black_box(clang_Module_getParent as *const ());
    black_box(clang_Module_getName as *const ());
    black_box(clang_Module_getFullName as *const ());
    black_box(clang_Module_isSystem as *const ());
    black_box(clang_Module_getNumTopLevelHeaders as *const ());
    black_box(clang_Module_getTopLevelHeader as *const ());
    black_box(clang_CXXConstructor_isConvertingConstructor as *const ());
    black_box(clang_CXXConstructor_isCopyConstructor as *const ());
    black_box(clang_CXXConstructor_isDefaultConstructor as *const ());
    black_box(clang_CXXConstructor_isMoveConstructor as *const ());
    black_box(clang_CXXField_isMutable as *const ());
    black_box(clang_CXXMethod_isDefaulted as *const ());
    #[cfg(any(feature = "clang_16_0", not(feature = "clang_14_0")))]
    black_box(clang_CXXMethod_isDeleted as *const ());
    black_box(clang_CXXMethod_isPureVirtual as *const ());
    black_box(clang_CXXMethod_isStatic as *const ());
    black_box(clang_CXXMethod_isVirtual as *const ());
    #[cfg(any(feature = "clang_16_0", not(feature = "clang_14_0")))]
    black_box(clang_CXXMethod_isCopyAssignmentOperator as *const ());
    #[cfg(any(feature = "clang_16_0", not(feature = "clang_14_0")))]
    black_box(clang_CXXMethod_isMoveAssignmentOperator as *const ());
    #[cfg(any(feature = "clang_17_0", not(feature = "clang_14_0")))]
    black_box(clang_CXXMethod_isExplicit as *const ());
    black_box(clang_CXXRecord_isAbstract as *const ());
    black_box(clang_EnumDecl_isScoped as *const ());
    black_box(clang_CXXMethod_isConst as *const ());
    black_box(clang_getTemplateCursorKind as *const ());
    black_box(clang_getSpecializedCursorTemplate as *const ());
    black_box(clang_getCursorReferenceNameRange as *const ());
    black_box(clang_getToken as *const ());
    black_box(clang_getTokenKind as *const ());
    black_box(clang_getTokenSpelling as *const ());
    black_box(clang_getTokenLocation as *const ());
    black_box(clang_getTokenExtent as *const ());
    black_box(clang_tokenize as *const ());
    black_box(clang_annotateTokens as *const ());
    black_box(clang_disposeTokens as *const ());
    black_box(clang_getCursorKindSpelling as *const ());
    black_box(clang_getDefinitionSpellingAndExtent as *const ());
    black_box(clang_enableStackTraces as *const ());
    black_box(clang_executeOnThread as *const ());
    black_box(clang_getCompletionChunkKind as *const ());
    black_box(clang_getCompletionChunkText as *const ());
    black_box(clang_getCompletionChunkCompletionString as *const ());
    black_box(clang_getNumCompletionChunks as *const ());
    black_box(clang_getCompletionPriority as *const ());
    black_box(clang_getCompletionAvailability as *const ());
    black_box(clang_getCompletionNumAnnotations as *const ());
    black_box(clang_getCompletionAnnotation as *const ());
    black_box(clang_getCompletionParent as *const ());
    black_box(clang_getCompletionBriefComment as *const ());
    black_box(clang_getCursorCompletionString as *const ());
    black_box(clang_getCompletionNumFixIts as *const ());
    black_box(clang_getCompletionFixIt as *const ());
    black_box(clang_defaultCodeCompleteOptions as *const ());
    black_box(clang_codeCompleteAt as *const ());
    black_box(clang_sortCodeCompletionResults as *const ());
    black_box(clang_disposeCodeCompleteResults as *const ());
    black_box(clang_codeCompleteGetNumDiagnostics as *const ());
    black_box(clang_codeCompleteGetDiagnostic as *const ());
    black_box(clang_codeCompleteGetContexts as *const ());
    black_box(clang_codeCompleteGetContainerKind as *const ());
    black_box(clang_codeCompleteGetContainerUSR as *const ());
    black_box(clang_codeCompleteGetObjCSelector as *const ());
    black_box(clang_getClangVersion as *const ());
    black_box(clang_toggleCrashRecovery as *const ());
    black_box(clang_getInclusions as *const ());
    black_box(clang_Cursor_Evaluate as *const ());
    black_box(clang_EvalResult_getKind as *const ());
    black_box(clang_EvalResult_getAsInt as *const ());
    black_box(clang_EvalResult_getAsLongLong as *const ());
    black_box(clang_EvalResult_isUnsignedInt as *const ());
    black_box(clang_EvalResult_getAsUnsigned as *const ());
    black_box(clang_EvalResult_getAsDouble as *const ());
    black_box(clang_EvalResult_getAsStr as *const ());
    black_box(clang_EvalResult_dispose as *const ());
    black_box(clang_findReferencesInFile as *const ());
    black_box(clang_findIncludesInFile as *const ());
    #[cfg(any(feature = "clang_17_0", not(feature = "clang_14_0")))]
    black_box(clang_findReferencesInFileWithBlock as *const ());
    #[cfg(any(feature = "clang_17_0", not(feature = "clang_14_0")))]
    black_box(clang_findIncludesInFileWithBlock as *const ());
    black_box(clang_index_isEntityObjCContainerKind as *const ());
    black_box(clang_index_getObjCContainerDeclInfo as *const ());
    black_box(clang_index_getObjCInterfaceDeclInfo as *const ());
    black_box(clang_index_getObjCCategoryDeclInfo as *const ());
    black_box(clang_index_getObjCProtocolRefListInfo as *const ());
    black_box(clang_index_getObjCPropertyDeclInfo as *const ());
    black_box(clang_index_getIBOutletCollectionAttrInfo as *const ());
    black_box(clang_index_getCXXClassDeclInfo as *const ());
    black_box(clang_index_getClientContainer as *const ());
    black_box(clang_index_setClientContainer as *const ());
    black_box(clang_index_getClientEntity as *const ());
    black_box(clang_index_setClientEntity as *const ());
    black_box(clang_IndexAction_create as *const ());
    black_box(clang_IndexAction_dispose as *const ());
    black_box(clang_indexSourceFile as *const ());
    black_box(clang_indexSourceFileFullArgv as *const ());
    black_box(clang_indexTranslationUnit as *const ());
    black_box(clang_indexLoc_getFileLocation as *const ());
    black_box(clang_indexLoc_getCXSourceLocation as *const ());
    black_box(clang_Type_visitFields as *const ());
    #[cfg(any(feature = "clang_20_0", not(feature = "clang_14_0")))]
    black_box(clang_visitCXXBaseClasses as *const ());
    #[cfg(any(feature = "clang_21_0", not(feature = "clang_14_0")))]
    black_box(clang_visitCXXMethods as *const ());
    #[cfg(any(feature = "clang_17_0", not(feature = "clang_14_0")))]
    black_box(clang_getBinaryOperatorKindSpelling as *const ());
    #[cfg(any(feature = "clang_17_0", not(feature = "clang_14_0")))]
    black_box(clang_getCursorBinaryOperatorKind as *const ());
    #[cfg(any(feature = "clang_17_0", not(feature = "clang_14_0")))]
    black_box(clang_getUnaryOperatorKindSpelling as *const ());
    #[cfg(any(feature = "clang_17_0", not(feature = "clang_14_0")))]
    black_box(clang_getCursorUnaryOperatorKind as *const ());
    black_box(clang_getRemappings as *const ());
    black_box(clang_getRemappingsFromFileList as *const ());
    black_box(clang_remap_getNumFiles as *const ());
    black_box(clang_remap_getFilenames as *const ());
    black_box(clang_remap_dispose as *const ());
    black_box(clang_Cursor_getParsedComment as *const ());
    black_box(clang_Comment_getKind as *const ());
    black_box(clang_Comment_getNumChildren as *const ());
    black_box(clang_Comment_getChild as *const ());
    black_box(clang_Comment_isWhitespace as *const ());
    black_box(clang_InlineContentComment_hasTrailingNewline as *const ());
    black_box(clang_TextComment_getText as *const ());
    black_box(clang_InlineCommandComment_getCommandName as *const ());
    black_box(clang_InlineCommandComment_getRenderKind as *const ());
    black_box(clang_InlineCommandComment_getNumArgs as *const ());
    black_box(clang_InlineCommandComment_getArgText as *const ());
    black_box(clang_HTMLTagComment_getTagName as *const ());
    black_box(clang_HTMLStartTagComment_isSelfClosing as *const ());
    black_box(clang_HTMLStartTag_getNumAttrs as *const ());
    black_box(clang_HTMLStartTag_getAttrName as *const ());
    black_box(clang_HTMLStartTag_getAttrValue as *const ());
    black_box(clang_BlockCommandComment_getCommandName as *const ());
    black_box(clang_BlockCommandComment_getNumArgs as *const ());
    black_box(clang_BlockCommandComment_getArgText as *const ());
    black_box(clang_BlockCommandComment_getParagraph as *const ());
    black_box(clang_ParamCommandComment_getParamName as *const ());
    black_box(clang_ParamCommandComment_isParamIndexValid as *const ());
    black_box(clang_ParamCommandComment_getParamIndex as *const ());
    black_box(clang_ParamCommandComment_isDirectionExplicit as *const ());
    black_box(clang_ParamCommandComment_getDirection as *const ());
    black_box(clang_TParamCommandComment_getParamName as *const ());
    black_box(clang_TParamCommandComment_isParamPositionValid as *const ());
    black_box(clang_TParamCommandComment_getDepth as *const ());
    black_box(clang_TParamCommandComment_getIndex as *const ());
    black_box(clang_VerbatimBlockLineComment_getText as *const ());
    black_box(clang_VerbatimLineComment_getText as *const ());
    black_box(clang_HTMLTagComment_getAsString as *const ());
    black_box(clang_FullComment_getAsHTML as *const ());
    black_box(clang_FullComment_getAsXML as *const ());
    #[cfg(any(feature = "clang_16_0", not(feature = "clang_14_0")))]
    black_box(clang_createAPISet as *const ());
    #[cfg(any(feature = "clang_16_0", not(feature = "clang_14_0")))]
    black_box(clang_disposeAPISet as *const ());
    #[cfg(any(feature = "clang_16_0", not(feature = "clang_14_0")))]
    black_box(clang_getSymbolGraphForUSR as *const ());
    #[cfg(any(feature = "clang_16_0", not(feature = "clang_14_0")))]
    black_box(clang_getSymbolGraphForCursor as *const ());
    black_box(clang_install_aborting_llvm_fatal_error_handler as *const ());
    black_box(clang_uninstall_llvm_fatal_error_handler as *const ());
    black_box(clang_CXRewriter_create as *const ());
    black_box(clang_CXRewriter_insertTextBefore as *const ());
    black_box(clang_CXRewriter_replaceText as *const ());
    black_box(clang_CXRewriter_removeText as *const ());
    black_box(clang_CXRewriter_overwriteChangedFiles as *const ());
    black_box(clang_CXRewriter_writeMainFileToStdOut as *const ());
    black_box(clang_CXRewriter_dispose as *const ());
}
